apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: keycloak-demo
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: Keycloak@2024!
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak-demo
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: Admin@2024!
